### ISSUE TITLE
[SETUP] SyntaxError: future feature annotations is not defined for Python version < 3.7

### ISSUE THREAD

**Issue by elvinaqa** [lux-org/lux#161]
```    from __future__ import annotations```

**Comment by dorisjlee** [comment]
Hi @elvinaqa, Could you elaborate on the details of this issue?

**Comment by viktorku** [comment]
Hi @dorisjlee, I also have this issue. It happens when I import the library:

```python
import lux
```

Resulting in this traceback:

```
Traceback (most recent call last):

  File "/Users/viktorku/miniconda3/envs/tagger/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-10-9dc1da9d19a2>", line 1, in <module>
    import lux

  File "/Users/viktorku/miniconda3/envs/tagger/lib/python3.6/site-packages/lux/__init__.py", line 17, in <module>
    from lux.core.frame import LuxDataFrame

  File "/Users/viktorku/miniconda3/envs/tagger/lib/python3.6/site-packages/lux/core/__init__.py", line 16, in <module>
    from .frame import LuxDataFrame

  File "/Users/viktorku/miniconda3/envs/tagger/lib/python3.6/site-packages/lux/core/frame.py", line 18, in <module>
    from lux.vis.Vis import Vis

  File "/Users/viktorku/miniconda3/envs/tagger/lib/python3.6/site-packages/lux/vis/Vis.py", line 15
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined
```

I'm using Python 3.6.6

**Comment by dorisjlee** [comment]
Hi @elvinaqa, @viktorku,  `__future__ annotations` is only supported in Python 3.7 and above, which explains why it is failing for Python 3.6.6 on your machine. I have removed this dependency in an [updated release](https://github.com/lux-org/lux/releases/tag/v0.2.1.1) to patch up this dependency issue.
You can try updating your lux installation via: 
```bash
pip install lux-api==0.2.1.1
```
Please let me know if this patch resolves the issue that you reported above.
