### ISSUE TITLE
[SETUP]  PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

### ISSUE THREAD

**Issue by WikiGenius** [lux-org/lux#187]
I have this problem after this command jupyter nbextension install --py luxwidget

Config option `kernel_spec_manager_class` not recognized by `InstallNBExtensionApp`.
Installing /home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/luxwidget/nbextension/static -> luxwidget
Traceback (most recent call last):
  File "/home/muhammed/anaconda3/envs/machine_learning/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/notebook/nbextensions.py", line 711, in start
    self.install_extensions()
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/notebook/nbextensions.py", line 682, in install_extensions
    full_dests = install(self.extra_args[0],
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/notebook/nbextensions.py", line 217, in install_nbextension_python
    full_dest = install_nbextension(
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/notebook/nbextensions.py", line 121, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/muhammed/anaconda3/envs/machine_learning/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

**Comment by dorisjlee** [comment]
Hi @WikiGenius, Thanks for your interest in Lux! To resolve this issue, use the command with the `--user` parameter instead: 
```bash
jupyter nbextension enable --py --user luxwidget
```
See the [troubleshooting page](https://lux-api.readthedocs.io/en/latest/source/getting_started/installation.html) for Lux installation for more detail. Let us know if this fixes the issue for you!

**Comment by WikiGenius** [comment]
Thanks @dorisjlee 
It has been solved 
with the --user parameter

**Comment by dorisjlee** [comment]
That's great to hear @WikiGenius! Feel free to reach out if you have any other questions or issues when using Lux!
