### ISSUE TITLE
[BUG] pandas._libs.hashtable.Int64HashTable.get_item KeyError: 0

### ISSUE THREAD

**Issue by LongUEH** [lux-org/lux#189]
When I write this code for this dataset I got a bug:

```
df.intent=['counts_of_ingredients']
df
```

Bug:

```
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues 

C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py:689: UserWarning:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1032, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1039, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 641, in _repr_html_
    self.maintain_recs()
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 472, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\action\custom.py", line 75, in custom_actions
    recommendation = lux.actions.__getattr__(action_name).action(ldf)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\action\enhance.py", line 67, in enhance
    vis.score = interestingness(vis, ldf)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\interestingness\interestingness.py", line 149, in interestingness
    chi2_score = chi2_contingency(contingency_table)[0] * 0.9 ** (
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\contingency.py", line 241, in chi2_contingency
    observed = np.asarray(observed)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 882, in __getitem__
    return self._get_value(key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 990, in _get_value
    loc = self.index.get_loc(label)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 0
```

This data come from the chocolate.csv with a kaggle link: https://www.kaggle.com/soroushghaderi/chocolate-bar-2020

**Comment by dorisjlee** [comment]
Hi @LongUEH, I was able to reproduce your error and fix this bug in the latest master branch. Here is what the result looks like after the bug fix. 
![image](https://user-images.githubusercontent.com/5554675/103182460-5b843100-48e6-11eb-9a43-919647afdb83.png)
We will incorporate this fix in the upcoming release. Thank you for raising this issue!

**Comment by LongUEH** [comment]
Wow nice. I'm looking forward to using lux again, when do you guys deploy it @dorisjlee ?

**Comment by dorisjlee** [comment]
Hi @LongUEH, I'm planning to merge in a couple more issues and fixes before the next mini-release, but hoping that we will roll it out sometime this week. Stay tuned!

**Comment by dorisjlee** [comment]
Hi @LongUEH, Thanks for the wait! I've added this fix into our most recent release. You can access these updated changes by upgrading to [the latest version of Lux](https://pypi.org/project/lux-api/0.2.2/):
```python
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Please let us know if this addresses the issue mentioned above. Feel free to let us know if there are any other questions that come up!
