### ISSUE TITLE
Falling back to Pandas display.

### ISSUE THREAD

**Issue by danilosantiago** [lux-org/lux#200]
C:\Anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues 

C:\Anaconda3\lib\site-packages\lux\core\frame.py:709: UserWarning:Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\lux\core\frame.py", line 661, in _repr_html_
    self.maintain_recs()
  File "C:\Anaconda3\lib\site-packages\lux\core\frame.py", line 492, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
  File "C:\Anaconda3\lib\site-packages\lux\action\custom.py", line 73, in custom_actions
    recommendation = lux.actions.__getattr__(action_name).action(ldf, args)
  File "C:\Anaconda3\lib\site-packages\lux\action\univariate.py", line 84, in univariate
    vlist = VisList(intent, ldf)
  File "C:\Anaconda3\lib\site-packages\lux\vis\VisList.py", line 43, in __init__
    self.refresh_source(self._source)
  File "C:\Anaconda3\lib\site-packages\lux\vis\VisList.py", line 313, in refresh_source
    ldf.executor.execute(self._collection, ldf)
  File "C:\Anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 97, in execute
    PandasExecutor.execute_aggregate(vis, isFiltered=filter_executed)
  File "C:\Anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 171, in execute_aggregate
    vis._vis_data = vis.data[[groupby_attr.attribute, "Record"]]
  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['Record'] not in index"

**Comment by dorisjlee** [comment]
Hi @danilosantiago,

This issue seems to be related to #181, which we just recently fixed in the latest version of Lux. 
You can access these changes by upgrading to [the latest version of Lux](https://pypi.org/project/lux-api/0.2.2/):
```python
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Please let us know if this addresses the issue mentioned above.
