### ISSUE TITLE
[BUG] Can't install Lux

### ISSUE THREAD

**Issue by hasansalimkanmaz** [lux-org/lux#296]
**Describe the bug**
I can't install lux to a new virtual env.

**To Reproduce**

```
(dataviz) (⎈ |dev-internal-aks-metamaze-eu:default)➜  Data Visualization pip freeze
(dataviz) (⎈ |dev-internal-aks-metamaze-eu:default)➜  Data Visualization pip install lux-api==0.2.3
Collecting lux-api==0.2.3
  Using cached lux-api-0.2.3.tar.gz (94 kB)
Collecting scipy>=1.3.3
  Using cached scipy-1.6.1-cp38-cp38-macosx_10_9_x86_64.whl (30.8 MB)
Collecting altair>=4.0.0
  Using cached altair-4.1.0-py3-none-any.whl (727 kB)
Collecting numpy>=1.16.5
  Using cached numpy-1.20.1-cp38-cp38-macosx_10_9_x86_64.whl (16.0 MB)
Collecting pandas>=1.1.0
  Using cached pandas-1.2.3-cp38-cp38-macosx_10_9_x86_64.whl (10.5 MB)
Collecting scikit-learn>=0.22
  Using cached scikit_learn-0.24.1-cp38-cp38-macosx_10_13_x86_64.whl (7.2 MB)
Collecting matplotlib>=3.0.0
  Using cached matplotlib-3.3.4-cp38-cp38-macosx_10_9_x86_64.whl (8.5 MB)
Collecting lux-widget>=0.1.4
  Using cached lux-widget-0.1.4.tar.gz (2.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/hsk/Company/environments/dataviz/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-install-jln93a9c/lux-widget/setup.py'"'"'; __file__='"'"'/private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-install-jln93a9c/lux-widget/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-pip-egg-info-vl5m7s2p
         cwd: /private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-install-jln93a9c/lux-widget/
    Complete output (77 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /Users/hsk/Company/environments/dataviz/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-wheel-i4l3cr42/pandocfilters/setup.py'"'"'; __file__='"'"'/private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-wheel-i4l3cr42/pandocfilters/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-wheel-lg2pmfua
           cwd: /private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-wheel-i4l3cr42/pandocfilters/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for pandocfilters
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/hsk/Company/environments/dataviz/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/tmps668xqb6', '--quiet', 'pandocfilters>=1.4.1']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/pip-install-jln93a9c/lux-widget/setup.py", line 106, in <module>
        setup(**setup_args)
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/hsk/Company/environments/dataviz/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/hsk/Company/environments/dataviz/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/q7/lkj02tgn2tz38b8glkk1ph8m0000gn/T/tmps668xqb6', '--quiet', 'pandocfilters>=1.4.1']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/hsk/Company/environments/dataviz/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by dorisjlee** [comment]
Hi @hasansalimkanmaz, Thanks for your question. This does not seem like an installation issue pertaining to Lux. It might be related to an outdated version of pip or `setuptools` (See this [issue](https://github.com/jupyter/jupyter/issues/507)). Please try upgrading your setuptools. If you are using conda, you might also want to install via `conda install -c conda-forge lux-api` instead of via pip. Let us know if this helps resolve the issue you're seeing!

**Comment by hasansalimkanmaz** [comment]
This already `pip install pandocfilters ` solved the issue. Thanks for your help.
