### ISSUE TITLE
Error in rendering Lux Widget

### ISSUE THREAD

**Issue by deepikamittal** [lux-org/lux#323]
I have installed the lux api using the following commands:

pip install lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget

The Jupyter nbextension list does include:
luxwidget/extension enabled
      - Validating: ok
      
However, when i read the csv file, it does not show the toggle option between lux and pandas
After using  lux.config.default_display='lux' , i get the following error

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues 

C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py:700: UserWarning:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 651, in _repr_html_
    self.maintain_recs()
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 480, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\action\custom.py", line 74, in custom_actions
    recommendation = lux.config.actions[action_name].action(ldf, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\action\univariate.py", line 96, in univariate
    vlist = VisList(intent, ldf)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\vis\VisList.py", line 43, in __init__
    self.refresh_source(self._source)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\vis\VisList.py", line 318, in refresh_source
    lux.config.executor.execute(self._collection, ldf)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 98, in execute
    PandasExecutor.execute_aggregate(vis, isFiltered=filter_executed)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 179, in execute_aggregate
    vis.data.groupby(groupby_attr.attribute, dropna=False, history=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 932, in groupby
    groupby_obj = super(LuxDataFrame, self).groupby(*args, **kwargs)
TypeError: groupby() got an unexpected keyword argument 'dropna'

**Comment by dorisjlee** [comment]
Hi @deepikamittal, Thank you for your interest in Lux and for reporting this issue! 
Could you share a screenshot of what happens when you print the dataframe in the simple example below?

```python
import pandas as pd
import lux
df = pd.read_csv("https://github.com/lux-org/lux-datasets/blob/master/data/employee.csv?raw=True")
df
```
You might also be interested in checking out [these troubleshooting tips](https://lux-api.readthedocs.io/en/latest/source/guide/FAQ.html#troubleshooting-tips) for why the Jupyter widget does not show up when a dataframe is printed. If the widget is printing correctly for the simple example, but you are still not able to get Lux to work on your own dataset. Please provide some details on what dataset you are using to help us debug what might have gone wrong.

**Comment by deepikamittal** [comment]
<img width="689" alt="Capture" src="https://user-images.githubusercontent.com/68030226/112839715-8cbff900-90af-11eb-96b5-21833c22c714.PNG">

**Comment by deepikamittal** [comment]
[general_data_1.zip](https://github.com/lux-org/lux/files/6221839/general_data_1.zip)

**Comment by deepikamittal** [comment]
I have shared the dataset and the snapshot of the error. Please help me resolve this.

**Comment by ksp987** [comment]
Hi, I am having the same issue with getting the ' toggle option'.
When I call df after importing CSV. It just gives the data frame as output. I am using chrome and my nbextensions list below. 
<img width="365" alt="Capture" src="https://user-images.githubusercontent.com/49786765/112910164-8af14680-913e-11eb-8936-2caebc23454b.PNG">
Please check. 

> Hi @deepikamittal, Thank you for your interest in Lux and for reporting this issue!
> Could you share a screenshot of what happens when you print the dataframe in the simple example below?
> 
> ```python
> import pandas as pd
> import lux
> df = pd.read_csv("https://github.com/lux-org/lux-datasets/blob/master/data/employee.csv?raw=True")
> df
> ```
> 
> You might also be interested in checking out [these troubleshooting tips](https://lux-api.readthedocs.io/en/latest/source/guide/FAQ.html#troubleshooting-tips) for why the Jupyter widget does not show up when a dataframe is printed. If the widget is printing correctly for the simple example, but you are still not able to get Lux to work on your own dataset. Please provide some details on what dataset you are using to help us debug what might have gone wrong.

**Comment by jinimukh** [comment]
Hi @ksp987 ! thanks for using Lux!

Could you also try the following commands and share a screenshot of the output? Thanks!
```
import pandas as pd
import lux
df = pd.read_csv("https://github.com/lux-org/lux-datasets/blob/master/data/employee.csv?raw=True")
df
```

**Comment by ksp987** [comment]
H @jinimukh 

Please check the screenshot
<img width="759" alt="Capture" src="https://user-images.githubusercontent.com/49786765/112946227-ff4cd980-9180-11eb-85ae-36df21dc535c.PNG">
.

**Comment by jinimukh** [comment]
Hi @ksp987, thanks for your response!

Are you using JupyterLab? If so, please run:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install luxwidget
````

Otherwise, your extension list looks alright, so I'm thinking that there was an issue with the lux installation. Let's try re-installing Lux. 
```
pip uninstall lux-api
pip uninstall lux-widget

pip install lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```

Could you also verify that `pip install lux-api` is successful?

**Comment by ksp987** [comment]
Thanks for your extended support @jinimukh. I am using jupyter notebook. 
I did the above steps to uninstall and install lux-API, but still no changes. 

I am still getting the same output without a toggle as below. 
https://github.com/lux-org/lux/issues/323#issuecomment-809963204

**Comment by ksp987** [comment]
Thank you all for your support. My issue was resolved. The mistake I did was using Anaconda jupyter notebook and trying to install lux by pip. 

**Resolution:** Uninstall anaconda and install jupyter with pip. 

Cheers!!

![image](https://user-images.githubusercontent.com/49786765/113220560-1d285480-92cf-11eb-954a-183bdc4afd02.png)
