### ISSUE TITLE
[BUG] `KeyError: 1` rendering Lux widget when using `matplotlib`

### ISSUE THREAD

**Issue by bwalchen** [lux-org/lux#380]
**Describe the bug**
Lux will consistently throw a rendering error when using `matplotlib` as the plotting backend. The errors are consistently reproducible and do not occur when using `altair` as the plotting backend.

**To Reproduce**
1. Save the following example data set as a CSV
```csv
u_id,result__value,result__display
random_id_1,false_positive,False Positive
random_id_2,,
random_id_3,misconfiguration,Misconfiguration
random_id_4,misconfiguration,Misconfiguration
random_id_5,false_positive,False Positive
random_id_6,instance_customization,Instance Customization
random_id_7,,
random_id_8,fixed,Fixed
random_id_9,fixed,Fixed
random_id_10,misconfiguration,Misconfiguration
random_id_11,false_positive,False Positive
```
2. Start a new Jupyter Lab Notebook
3. Replace the `CSV_PATH` variable below with your new csv, run the code, and see the error
```py
import pandas as pd
import lux
lux.config.plotting_backend = "matplotlib"

# Import the CSV that is above
df = pd.read_csv(<CSV_PATH>)

# Attempt to render it in Lux widget
df[['result__display', 'u_id']]
```

**Expected behavior**
Widget would render and no error would be displayed.

**Additional context**
Interestingly the error does not occur if I do either of the following:
* change plotting back end to altair: `lux.config.plotting_backend = "altair"`
* only target one column instead of two like such `df[['result__display']]`

**Screenshots**
Below is the stacktrace:
```
/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/IPython/core/formatters.py:918: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues 

/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/core/frame.py:609: UserWarning:Traceback (most recent call last):
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1625, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1632, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/core/frame.py", line 571, in _ipython_display_
    self.maintain_recs()
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/core/frame.py", line 429, in maintain_recs
    self._widget = rec_df.render_widget()
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/core/frame.py", line 658, in render_widget
    widgetJSON = self.to_JSON(self._rec_info, input_current_vis=input_current_vis)
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/core/frame.py", line 689, in to_JSON
    widget_spec["current_vis"] = LuxDataFrame.current_vis_to_JSON(
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/core/frame.py", line 706, in current_vis_to_JSON
    current_vis_spec = vlist[0].to_code(language=lux.config.plotting_backend, prettyOutput=False)
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/vis/Vis.py", line 314, in to_code
    return self._to_matplotlib_svg()
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/vis/Vis.py", line 268, in _to_matplotlib_svg
    self._code = renderer.create_vis(self)
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/vislib/matplotlib/MatplotlibRenderer.py", line 78, in create_vis
    chart = BarChart(vis, fig, ax)
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/vislib/matplotlib/BarChart.py", line 37, in __init__
    super().__init__(dobj, fig, ax)
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/vislib/matplotlib/MatplotlibChart.py", line 39, in __init__
    self.chart = self.initialize_chart()
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/lux/vislib/matplotlib/BarChart.py", line 101, in initialize_chart
    d_x[colors[i]].append(bars[i])
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 853, in __getitem__
    return self._get_value(key)
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "/Users/cool.user/Documents/projects/security-research/.venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 1
```

**Comment by bwalchen** [comment]
Forgot to mention this in the bug report:

Thanks for this really cool project y'all put together. It's been a blast using is for rapid data analysis 🙂

**Comment by dorisjlee** [comment]
Thanks for reporting this @bwalchen! We're looking into this issue and will get back to you soon when we push out the fix!

**Comment by dorisjlee** [comment]
Hi @bwalchen, Thanks for your patience, I fixed this bug in the latest release. 
You can access these updated changes by upgrading to [the latest version of Lux](https://pypi.org/project/lux-api/):
```python
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
I hope that this resolves the problem that you were seeing. Also, if you prefer using the `matplotlib` renderer for your analysis over `altair`, let us know! The Altair renderer is slightly more mature and stable, but we're looking forward to building out the matplotlib more soon!
