### ISSUE TITLE
[BUG] Import Orange Problem

### ISSUE THREAD

**Issue by lyiikl** [lux-org/lux#381]
**Describe the bug**
When `import Orange` with lux in jupyter lab, lux had an unexpected error (as the image below)

**To Reproduce**
```
C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\core\frame.py:628: UserWarning:Traceback (most recent call last):
  File "C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\core\frame.py", line 590, in _ipython_display_
    self.maintain_recs()
  File "C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\core\frame.py", line 432, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
  File "C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\action\custom.py", line 74, in custom_actions
    recommendation = lux.config.actions[action_name].action(ldf, args)
  File "C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\action\univariate.py", line 95, in univariate
    vlist = VisList(intent, ldf)
  File "C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\vis\VisList.py", line 43, in __init__
    self.refresh_source(self._source)
  File "C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\vis\VisList.py", line 336, in refresh_source
    lux.config.executor.execute(self._collection, ldf, approx=approx)
  File "C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\executor\PandasExecutor.py", line 134, in execute
    PandasExecutor.execute_aggregate(vis, isFiltered=filter_executed)
  File "C:\Users\Yi\Anaconda3\envs\automl\lib\site-packages\lux\executor\PandasExecutor.py", line 180, in execute_aggregate
    if groupby_attr.attribute in vis.data.unique_values.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

```

**Screenshots**
![image](https://user-images.githubusercontent.com/4361693/121459851-92ef2180-c9de-11eb-8a1e-4b2818de6fa8.png)

**Additional context**
This seems to be caused due to package conflicts.
What should I do to fix it?

**Comment by dorisjlee** [comment]
Thanks for your question @lyiikl ! Based on the error message, this doesn't seem like an issue caused by package conflicts. Could you let me know if this issue shows up if `import Orange` is not added in the first line?

**Comment by lyiikl** [comment]
> Thanks for your question @lyiikl ! Based on the error message, this doesn't seem like an issue caused by package conflicts. Could you let me know if this issue shows up if `import Orange` is not added in the first line?
