### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by belkmouf** [lux-org/lux#473]
**Describe the bug**
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py:918: UserWarning: Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display. Please report the following issue on Github: https://github.com/lux-org/lux/issues   C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py:632: UserWarning:Traceback (most recent call last):   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 594, in _ipython_display_     self.maintain_recs()   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 436, in maintain_recs     custom_action_collection = custom_actions(rec_df)   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\action\custom.py", line 74, in custom_actions     recommendation = lux.config.actions[action_name].action(ldf, args)   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\action\univariate.py", line 95, in univariate     vlist = VisList(intent, ldf)   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\vis\VisList.py", line 43, in __init__     self.refresh_source(self._source)   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\vis\VisList.py", line 336, in refresh_source     lux.config.executor.execute(self._collection, ldf, approx=approx)   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 138, in execute     PandasExecutor.execute_aggregate(vis, isFiltered=filter_executed)   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 211, in execute_aggregate     vis._vis_data = (vis.data.groupby(groupby_attr.attribute, dropna=False, history=False).count().reset_index().rename(columns={index_name: "Record"}))   File "C:\ProgramData\Anaconda3\lib\site-packages\lux\core\frame.py", line 867, in groupby     groupby_obj = super(LuxDataFrame, self).groupby(*args, **kwargs) TypeError: groupby() got an unexpected keyword argument 'dropna'
**To Reproduce**
Please describe the steps needed to reproduce the behavior. For example:
1. Using this data: `df = ...`
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Important**: Make sure to provide a sample of (preferably synthetic) data 
that can trigger the error based on the instructions.

**Expected behavior**

**Screenshots**

**Debugging information**
Please run the following code in your Jupyter Notebook/Lab:

```python
import lux
lux.debug_info()
```

**Additional context**

**Comment by dorisjlee** [comment]
Hi @belkmouf, Could you provide more information about what led to this error?
