### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by baniasbaabe** [lux-org/lux#483]
When trying to install the package via `pip install lux-api` the following error occurs:

```
ERROR: Command errored out with exit status 1:
     command: 'c:\code\eda_research\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\I574778\\AppData\\Local\\Temp\\pip-install-3uvkz52y\\sh\\setup.py'"'"'; __file__='"'"'C:\\Users\\I574778\\AppData\\Local\\Temp\\pip-install-3uvkz52y\\sh\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\I574778\AppData\Local\Temp\pip-pip-egg-info-arz193lv'
         cwd: C:\Users\I574778\AppData\Local\Temp\pip-install-3uvkz52y\sh\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\I574778\AppData\Local\Temp\pip-install-3uvkz52y\sh\setup.py", line 5, in <module>
        import sh
      File "C:\Users\I574778\AppData\Local\Temp\pip-install-3uvkz52y\sh\sh.py", line 37, in <module>
        import fcntl
    ModuleNotFoundError: No module named 'fcntl'
```

I'm using `Python==3.8.9`.

**Comment by Greco1899** [comment]
``` 
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\<windows_user>\AppData\Local\Temp\pip-install-neq3f8qo\sh_36306239465a4240a3b21385a74af710\setup.py", line 5, in <module>
          import sh
        File "C:\Users\<windows_user>\AppData\Local\Temp\pip-install-neq3f8qo\sh_36306239465a4240a3b21385a74af710\sh.py", line 37, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I'm facing the same issue on Windows 10.

**Comment by chandler20708** [comment]
same problem here

**Comment by dch0319** [comment]
same problem here

**Comment by dekristi** [comment]
Unfortunately the same issue:
     import sh
     
        import fcntl
    ModuleNotFoundError: No module named 'fcntl'

**Comment by MichlF** [comment]
Same

**Comment by OmbrettaBistoni** [comment]
No solutions here? I have the same issue

**Comment by dekristi** [comment]
This problem is solved in Python 3.11  fcntl — The fcntl and ioctl system
calls — Python 3.11.1 documentation
<https://docs.python.org/3/library/fcntl.html>

**Comment by OmbrettaBistoni** [comment]
@dekristi not working for me, even with python 3.11. I have Windows 10

**Comment by dekristi** [comment]
I think it's still Windows problem. Some use Docker to install a
package  ModuleNotFoundError:
No module named 'fcntl' · Issue #1414 · doccano/doccano (github.com)
<https://github.com/doccano/doccano/issues/1414> you can try it!

**Comment by madisondevin** [comment]
I'm having the same issue, and can't install lux on a Windows 11 computer. So lux just can't be installed on Windows? Suggestions welcomed (I don't use Docker).
